2020-12-16 12:25:49,835 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 13, in question
    form = get_form(formtype)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\forms.py", line 41, in get_form
    return string_to_form[formtype]()
KeyError: 'open'
2020-12-16 12:26:51,582 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 13, in question
    form = get_form(formtype)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\forms.py", line 41, in get_form
    return string_to_form[formtype]()
KeyError: 'open'
2020-12-16 12:26:51,582 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 13, in question
    form = get_form(formtype)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\forms.py", line 41, in get_form
    return string_to_form[formtype]()
KeyError: 'open'
