2020-12-16 11:55:08,566 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 12, in question
    form = QuestionType.query().get(Question.questiontype).form  #OpenQuestionForm()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\loading.py", line 234, in load_on_pk_identity
    if None in primary_key_identity:
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\sql\elements.py", line 3275, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
2020-12-16 11:55:40,488 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 12, in question
    q_type = QuestionType.query().get(Question.questiontype) #OpenQuestionForm()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\loading.py", line 234, in load_on_pk_identity
    if None in primary_key_identity:
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\sql\elements.py", line 3275, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
2020-12-16 11:55:40,488 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 12, in question
    q_type = QuestionType.query().get(Question.questiontype) #OpenQuestionForm()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\orm\loading.py", line 234, in load_on_pk_identity
    if None in primary_key_identity:
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\sqlalchemy\sql\elements.py", line 3275, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
2020-12-16 11:57:50,519 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 13, in question
    form = q_type.form
AttributeError: 'BaseQuery' object has no attribute 'form'
2020-12-16 11:57:50,519 ERROR: Exception on /questionlist/0 [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/0]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 13, in question
    form = q_type.form
AttributeError: 'BaseQuery' object has no attribute 'form'
